const desserts = [
  "Affogato",
  "Apple Pie",
  "Aztec Chocolate Ice Cream",
  "Baked Alaska",
  "Baklava",
  "Banana Pudding",
  "Bananas Foster",
  "Bear Claw",
  "Beignets",
  "Black Sesame Ice Cream",
  "Blondie",
  "Blueberry Pie",
  "Boston Cream Pie",
  "Bread Pudding",
  "Brown Sugar Cookie",
  "Brownie",
  "Bubble Tea",
  "Bubur Cha Cha",
  "Candied Apple",
  "Cannoli",
  "Carrot Cake",
  "Cendol",
  "Chocolate Babka",
  "Chocolate Chip Cookie",
  "Churro",
  "Cider Donut",
  "Cinnamon Roll",
  "Cornbread",
  "Cream Puff",
  "Creme Brulee",
  "Crepe",
  "Cronut",
  "Cruller",
  "Dippin' Dots",
  "Donut",
  "Eclair",
  "Egg Custard Tart",
  "Flan",
  "Fluffy Pancake",
  "Frozn Yogurt",
  "Funnel Cake",
  "Gingerbread",
  "Girl Scout Cookie",
  "Gooey Butter Cake",
  "Granita",
  "Grass Jelly",
  "Ice Cream Sandwich",
  "Ice Kacang",
  "Jell-O",
  "Key Lime Pie",
  "Lemon Bar",
  "Macaron",
  "Madeleines",
  "Mango Sticky Rice",
  "Marble Cake",
  "Millefeuille",
  "Mochi",
  "Nanaimo Bar",
  "New York Cheesecake",
  "Pancake",
  "Pandan Cake",
  "Panna Cotta",
  "Peach Cobbler",
  "Pecan Pie",
  "Pineapple Bun",
  "Pineapple Upside Down Cake",
  "Pumpkin Pie",
  "Raspberry Crumble",
  "Red Velvet Cake",
  "Root Beer Float",
  "S'more",
  "Shortbread",
  "Snickerdoodle",
  "Sopapilla",
  "Steamed Custard Buns",
  "Sticky Bun",
  "Strawberry Shortcake",
  "Stroopwafel",
  "Tang Yuen",
  "Tapioca Pudding",
  "Tiramisu",
  "Tres Leches",
  "Truffles",
  "Waffle",
  "Zucchini Bread",
];

module.exports = desserts;
